; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=80948371-1ae7-4f1c-a0ef-b9dd459d5f03
AppName=test_libmpv
AppVersion=2024.12.18
DefaultDirName={autopf64}\test_libmpv
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=test_libmpv
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=test_libmpv
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=test_libmpv
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.12.18"
VersionInfoProductVersion="2024.12.18.0"
VersionInfoTextVersion="v2024.12.18"
VersionInfoVersion="2024.12.18.0"
VersionInfoProductName="test_libmpv - Package 2024.12.18"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows-static\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\test_libmpv"; Filename: "{app}\test_libmpv.exe"
Name: "{group}\{cm:UninstallProgram,test_libmpv}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\test_libmpv"; Filename: "{app}\test_libmpv.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
