; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=438f3e86-3f2f-4318-9c9d-8f07aa893eb4
AppName=test_workspace
AppVersion=2024.11.25
DefaultDirName={autopf64}\test_workspace
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=test_workspace
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=test_workspace
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=test_workspace
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.11.25"
VersionInfoProductVersion="2024.11.25.0"
VersionInfoTextVersion="v2024.11.25"
VersionInfoVersion="2024.11.25.0"
VersionInfoProductName="test_workspace - Package 2024.11.25"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\test_workspace"; Filename: "{app}\test_workspace.exe"
Name: "{group}\{cm:UninstallProgram,test_workspace}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\test_workspace"; Filename: "{app}\test_workspace.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
