; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=d0ad1be1-eeb6-49a8-965e-b699a03f3508
AppName=test_clang
AppVersion=2024.11.28
DefaultDirName={autopf64}\test_clang
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=test_clang
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=test_clang
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=test_clang
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.11.28"
VersionInfoProductVersion="2024.11.28.0"
VersionInfoTextVersion="v2024.11.28"
VersionInfoVersion="2024.11.28.0"
VersionInfoProductName="test_clang - Package 2024.11.28"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\test_clang"; Filename: "{app}\test_clang.exe"
Name: "{group}\{cm:UninstallProgram,test_clang}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\test_clang"; Filename: "{app}\test_clang.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
