; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=27e30bcd-23f1-4d4a-bcae-ad62458475fa
AppName=tms_missing_deps
AppVersion=2024.12.11
DefaultDirName={autopf64}\tms_missing_deps
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=tms_missing_deps
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=tms_missing_deps
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=tms_missing_deps
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.12.11"
VersionInfoProductVersion="2024.12.11.0"
VersionInfoTextVersion="v2024.12.11"
VersionInfoVersion="2024.12.11.0"
VersionInfoProductName="tms_missing_deps - Package 2024.12.11"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows-static\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\tms_missing_deps"; Filename: "{app}\tms_missing_deps.exe"
Name: "{group}\{cm:UninstallProgram,tms_missing_deps}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\tms_missing_deps"; Filename: "{app}\tms_missing_deps.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
