; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
MinVersion=6.1.7600
AppId=5e9d0764-30b7-4b87-8a53-8fd6e56d2885
AppName=test_package
AppVersion=2024.11.25
DefaultDirName={autopf64}\test_package
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=test_package
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=test_package
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=test_package
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.11.25"
VersionInfoProductVersion="2024.11.25.0"
VersionInfoTextVersion="v2024.11.25"
VersionInfoVersion="2024.11.25.0"
VersionInfoProductName="test_package - Package 2024.11.25"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\test_package"; Filename: "{app}\test_package.exe"
Name: "{group}\{cm:UninstallProgram,test_package}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\test_package"; Filename: "{app}\test_package.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
