; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=852480b3-fec0-4b31-9916-b4859daa56a5
AppName=test_libuv
AppVersion=2024.12.5
DefaultDirName={autopf64}\test_libuv
UsePreviousAppDir=no
DisableDirPage=no
DefaultGroupName=test_libuv
AllowNoIcons=yes
DisableFinishedPage=yes
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir=.\target
OutputBaseFilename=test_libuv
;SetupIconFile=setup.ico
Uninstallable=yes
;UninstallDisplayIcon=setup.ico
UninstallDisplayName=test_libuv
CreateUninstallRegKey=no
Compression=lzma/ultra64   
SolidCompression=yes
ArchitecturesAllowed=x64os arm64
ArchitecturesInstallIn64BitMode=x64os arm64
WizardStyle=modern
AlwaysRestart=no
RestartIfNeededByRun=no
VersionInfoProductTextVersion="v2024.12.5"
VersionInfoProductVersion="2024.12.5.0"
VersionInfoTextVersion="v2024.12.5"
VersionInfoVersion="2024.12.5.0"
VersionInfoProductName="test_libuv - Package 2024.12.5"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Files]
Source: "target\installed\x64-windows\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\test_libuv"; Filename: "{app}\test_libuv.exe"
Name: "{group}\{cm:UninstallProgram,test_libuv}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\test_libuv"; Filename: "{app}\test_libuv.exe"; Tasks: desktopicon


[InstallDelete]
Type: filesandordirs; Name: "{app}"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"
